"""
RenertPy Python Package
Copyright (C) 2022 Assaf Gordon (assafgordon@gmail.com)
License: BSD (See LICENSE file)
"""

import os
import copy

capital_cities = {
    'Afghanistan': 'Kabul',
    'Albania': 'Tirana (Tirane)',
    'Algeria': 'Algiers',
    'Andorra': 'Andorra la Vella',
    'Angola': 'Luanda',
    'Antigua and Barbuda': 'Saint John\'s',
    'Argentina': 'Buenos Aires',
    'Armenia': 'Yerevan',
    'Australia': 'Canberra',
    'Austria': 'Vienna',
    'Azerbaijan': 'Baku',
    'Bahamas': 'Nassau',
    'Bahrain': 'Manama',
    'Bangladesh': 'Dhaka',
    'Barbados': 'Bridgetown',
    'Belarus': 'Minsk',
    'Belgium': 'Brussels',
    'Belize': 'Belmopan',
    'Benin': 'Porto Novo[1]',
    'Bhutan': 'Thimphu',
    'Bolivia': 'La Paz (administrative), Sucre (official)',
    'Bosnia and Herzegovina': 'Sarajevo',
    'Botswana': 'Gaborone',
    'Brazil': 'Brasilia',
    'Brunei': 'Bandar Seri Begawan',
    'Bulgaria': 'Sofia',
    'Burkina Faso': 'Ouagadougou',
    'Burundi': 'Gitega',
    'Cambodia': 'Phnom Penh',
    'Cameroon': 'Yaounde',
    'Canada': 'Ottawa',
    'Cape Verde': 'Praia',
    'Central African Republic': 'Bangui',
    'Chad': 'N\'Djamena',
    'Chile': 'Santiago',
    'China': 'Beijing',
    'Colombia': 'Bogota',
    'Comoros': 'Moroni',
    'Congo, Democratic Republic of the': 'Kinshasa',
    'Congo, Republic of the': 'Brazzaville',
    'Costa Rica': 'San Jose',
    'Côte d\'Ivoire (Ivory Coast)': 'Yamoussoukro',
    'Croatia': 'Zagreb',
    'Cuba': 'Havana',
    'Cyprus': 'Nicosia',
    'Czech Republic (Czechia)': 'Prague',
    'Denmark': 'Copenhagen',
    'Djibouti': 'Djibouti',
    'Dominica': 'Roseau',
    'Dominican Republic': 'Santo Domingo',
    'East Timor': 'Dili',
    'Ecuador': 'Quito',
    'Egypt': 'Cairo',
    'El Salvador': 'San Salvador',
    'England[6]': 'London',
    'Equatorial Guinea': 'Malabo',
    'Eritrea': 'Asmara',
    'Estonia': 'Tallinn',
    'Eswatini (Swaziland)[7]': 'Mbabana[8]',
    'Ethiopia': 'Addis Ababa',
    'Federated States of Micronesia': 'Palikir',
    'Fiji': 'Suva',
    'Finland': 'Helsinki',
    'France': 'Paris',
    'Gabon': 'Libreville',
    'Gambia': 'Banjul',
    'Georgia': 'Tbilisi',
    'Germany': 'Berlin',
    'Ghana': 'Accra',
    'Greece': 'Athens',
    'Grenada': 'Saint George\'s',
    'Guatemala': 'Guatemala City',
    'Guinea': 'Conakry',
    'Guinea-Bissau': 'Bissau',
    'Guyana': 'Georgetown',
    'Haiti': 'Port au Prince',
    'Honduras': 'Tegucigalpa',
    'Hungary': 'Budapest',
    'Iceland': 'Reykjavik',
    'India': 'New Delhi',
    'Indonesia': 'Jakarta',
    'Iran': 'Tehran',
    'Iraq': 'Baghdad',
    'Ireland': 'Dublin',
    'Israel': 'Jerusalem',
    'Italy': 'Rome',
    'Jamaica': 'Kingston',
    'Japan': 'Tokyo',
    'Jordan': 'Amman',
    'Kazakhstan': 'Nur-Sultan',
    'Kenya': 'Nairobi',
    'Kiribati': 'Tarawa Atoll',
    'Kosovo': 'Pristina',
    'Kuwait': 'Kuwait City',
    'Kyrgyzstan': 'Bishkek',
    'Laos': 'Vientiane',
    'Latvia': 'Riga',
    'Lebanon': 'Beirut',
    'Lesotho': 'Maseru',
    'Liberia': 'Monrovia',
    'Libya': 'Tripoli',
    'Liechtenstein': 'Vaduz',
    'Lithuania': 'Vilnius',
    'Luxembourg': 'Luxembourg',
    'Madagascar': 'Antananarivo',
    'Malawi': 'Lilongwe',
    'Malaysia': 'Kuala Lumpur',
    'Maldives': 'Male',
    'Mali': 'Bamako',
    'Malta': 'Valletta',
    'Marshall Islands': 'Majuro',
    'Mauritania': 'Nouakchott',
    'Mauritius': 'Port Louis',
    'Mexico': 'Mexico City',
    'Moldova': 'Chisinau',
    'Monaco': 'Monaco',
    'Mongolia': 'Ulaanbaatar',
    'Montenegro': 'Podgorica',
    'Morocco': 'Rabat',
    'Mozambique': 'Maputo',
    'Myanmar (Burma)': 'Nay Pyi Taw',
    'Namibia': 'Windhoek',
    'Nauru': 'No official capital',
    'Nepal': 'Kathmandu',
    'Netherlands': 'Amsterdam[13]',
    'New Zealand': 'Wellington',
    'Nicaragua': 'Managua',
    'Niger': 'Niamey',
    'Nigeria': 'Abuja',
    'North Korea': 'Pyongyang',
    'North Macedonia (Macedonia)': 'Skopje',
    'Northern Ireland[15]': 'Belfast',
    'Norway': 'Oslo',
    'Oman': 'Muscat',
    'Pakistan': 'Islamabad',
    'Palau': 'Melekeok',
    'Panama': 'Panama City',
    'Papua New Guinea': 'Port Moresby',
    'Paraguay': 'Asuncion',
    'Peru': 'Lima',
    'Philippines': 'Manila',
    'Poland': 'Warsaw',
    'Portugal': 'Lisbon',
    'Qatar': 'Doha',
    'Romania': 'Bucharest',
    'Russia': 'Moscow',
    'Rwanda': 'Kigali',
    'Saint Kitts and Nevis': 'Basseterre',
    'Saint Lucia': 'Castries',
    'Saint Vincent and the Grenadines': 'Kingstown',
    'Samoa': 'Apia',
    'San Marino': 'San Marino',
    'Sao Tome and Principe': 'Sao Tome',
    'Saudi Arabia': 'Riyadh',
    'Scotland[16]': 'Edinburgh',
    'Senegal': 'Dakar',
    'Serbia': 'Belgrade',
    'Seychelles': 'Victoria',
    'Sierra Leone': 'Freetown',
    'Singapore': 'Singapore',
    'Slovakia': 'Bratislava',
    'Slovenia': 'Ljubljana',
    'Solomon Islands': 'Honiara',
    'Somalia': 'Mogadishu',
    'South Africa': 'Pretoria, Bloemfontein, Cape Town',
    'South Korea': 'Seoul',
    'South Sudan': 'Juba',
    'Spain': 'Madrid',
    'Sri Lanka': 'Sri Jayawardenapura Kotte',
    'Sudan': 'Khartoum',
    'Suriname': 'Paramaribo',
    'Sweden': 'Stockholm',
    'Switzerland': 'Bern',
    'Syria': 'Damascus',
    'Taiwan': 'Taipei',
    'Tajikistan': 'Dushanbe',
    'Tanzania': 'Dodoma',
    'Thailand': 'Bangkok',
    'Togo': 'Lome',
    'Tonga': 'Nuku\'alofa',
    'Trinidad and Tobago': 'Port of Spain',
    'Tunisia': 'Tunis',
    'Türkiye (Turkey)': 'Ankara',
    'Turkmenistan': 'Ashgabat',
    'Tuvalu': 'Funafuti',
    'Uganda': 'Kampala',
    'Ukraine': 'Kyiv or Kiev',
    'United Arab Emirates': 'Abu Dhabi',
    'United Kingdom': 'London',
    'United States': 'Washington D.C.',
    'Uruguay': 'Montevideo',
    'Uzbekistan': 'Tashkent',
    'Vanuatu': 'Port Vila',
    'Vatican City': 'Vatican City',
    'Venezuela': 'Caracas',
    'Vietnam': 'Hanoi',
    'Wales[23]': 'Cardiff',
    'Yemen': 'Sana\'a',
    'Zambia': 'Lusaka',
    'Zimbabwe': 'Harare'
        }

def get_capital_cities():
    return copy.deepcopy(capital_cities)


pokemon_abilities = {
    "Air Lock": "Eliminates the effects of weather.",
    "Arena Trap": "Prevents non-Flying-type opposing Pokémon from fleeing.",
    "Battle Armor": "Protects the Pokémon from critical hits.",
    "Blaze": "Powers up Fire-type moves when the Pokémon's HP is low.",
    "Cacophony": "The Pokémon is immune to sound-based moves.",
    "Chlorophyll": "Boosts the Pokémon's Speed stat in harsh sunlight.",
    "Clear Body": "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.",
    "Cloud Nine": "Eliminates the effects of weather.",
    "Color Change": "The Pokémon's type becomes the type of the move used on it.",
    "Compound Eyes": "Boosts the Pokémon's Accuracy stat.",
    "Cute Charm": "Contact with the Pokémon may cause infatuation.",
    "Damp": "Prevents the use of Explosion and Self-Destruct.",
    "Drizzle": "Activates rain when the Pokémon enters battle.",
    "Drought": "Activates harsh sunlight when the Pokémon enters battle.",
    "Early Bird": "The Pokémon awakens twice as fast from sleep.",
    "Effect Spore": "Contact with the Pokémon may inflict poison, sleep, or paralysis on its attacker.",
    "Flame Body": "Contact with the Pokémon may inflict burn the attacker.",
    "Flash Fire": "Powers up the Pokémon's Fire-type moves if hit by a Fire-type move.",
    "Forecast": "The Pokémon transforms with the weather to change its type to Water, Fire, or Ice.",
    "Guts": "Boosts the Pokémon's Attack stat when it has a status condition.",
    "Huge Power": "Doubles the Pokémon's Attack stat.",
    "Hustle": "Boosts the Pokémon's Attack stat but lowers the Pokémon's Accuracy stat.",
    "Hyper Cutter": "The Pokémon's Attack stat cannot be lowered by other Pokémon.",
    "Illuminate": "Raises the likelihood of meeting wild Pokémon outside of battle.",
    "Immunity": "The Pokémon cannot be poisoned.",
    "Inner Focus": "The Pokémon cannot flinch.",
    "Insomnia": "The Pokémon cannot sleep.",
    "Intimidate": "When the Pokémon enters battle, it lowers opposing Pokémon's Attack stats.",
    "Keen Eye": "The Pokémon's Accuracy stat cannot be lowered by other Pokémon.",
    "Levitate": "The Pokémon is immune to Ground-type moves and Abilities.",
    "Lightning Rod": "The Pokémon draws in all Electric-type moves. Instead of receiving damage by Electric-type moves, it boosts the Pokémon's Sp. Atk.",
    "Limber": "The Pokémon cannot be paralyzed.",
    "Liquid Ooze": "HP draining moves used on the Pokémon damage instead of heal.",
    "Magma Armor": "The Pokémon cannot be frozen.",
    "Magnet Pull": "Prevents Steel-type opposing Pokémon from fleeing.",
    "Marvel Scale": "Boosts the Pokémon's Defense stat when it has a status condition.",
    "Minus": "Boosts the Pokémon's Sp. Atk if an ally with the Plus or Minus Ability is also in battle.",
    "Natural Cure": "The Pokémon loses any status condition after switching out.",
    "Oblivious": "The Pokémon cannot be infatuated or taunted.",
    "Overgrow": "Powers up Grass-type moves when the Pokémon's HP is low.",
    "Own Tempo": "The Pokémon cannot be confused.",
    "Pickup": "The Pokémon may pick up the item an opposing Pokémon used during a battle. The Pokémon may also pick up items outside of battle.",
    "Plus": "Boosts the Pokémon's Sp. Atk if an ally with the Plus or Minus Ability is also in battle.",
    "Poison Point": "Contact with the Pokémon may poison the attacker.",
    "Pressure": "Raises opposing Pokémon's PP usage.",
    "Pure Power": "Doubles the Pokémon's Attack stat.",
    "Rain Dish": "The Pokémon gradually regains HP in rain.",
    "Rock Head": "Protects the Pokémon from recoil damage.",
    "Rough Skin": "Contact with the Pokémon will damage the attacker.",
    "Run Away": "Enables a sure getaway from wild Pokémon.",
    "Sand Stream": "Activates sandstorm when the Pokémon enters battle.",
    "Sand Veil": "Boosts the Pokémon's Evasion stat in a sandstorm.",
    "Serene Grace": "Boosts the likelihood of additional effects occurring when attacking.",
    "Shadow Tag": "Prevents opposing Pokémon from fleeing.",
    "Shed Skin": "The Pokémon may heal its status condition.",
    "Shell Armor": "Protects the Pokémon from critical hits.",
    "Shield Dust": "Protects the Pokémon from additional effects.",
    "Soundproof": "The Pokémon is immune to sound-based moves.",
    "Speed Boost": "The Pokémon's Speed stat is boosted every turn.",
    "Static": "Contact with the Pokémon may paralyze the attacker.",
    "Stench": "Lowers the likelihood of meeting wild Pokémon outside of battle. The Pokémon may also cause a Pokémon to flinch after attacking it.",
    "Sticky Hold": "The Pokémon's item cannot be removed.",
    "Sturdy": "The Pokémon is immune to one-hit KO moves. The Pokémon cannot be knocked out with one hit while at full health either.",
    "Suction Cups": "The Pokémon cannot be forced to switch out or flee.",
    "Swarm": "Powers up Bug-type moves when the Pokémon's HP is low.",
    "Swift Swim": "Boosts the Pokémon's Speed stat in rain.",
    "Synchronize": "The attacker will receive the same status condition if it inflicts a burn, poison, or paralysis to the Pokémon.",
    "Thick Fat": "The Pokémon receives half damage from Fire and Ice-type moves.",
    "Torrent": "Powers up Water-type moves when the Pokémon's HP is low.",
    "Trace": "Copies an opposing Pokémon's Ability.",
    "Truant": "The Pokémon cannot use a move two turns in a row.",
    "Vital Spirit": "The Pokémon cannot sleep.",
    "Volt Absorb": "Restores the Pokémon's HP when hit by an Electric-type move, instead of taking damage.",
    "Water Absorb": "Restores the Pokémon's HP when hit by a Water-type move, instead of taking damage.",
    "Water Veil": "The Pokémon cannot be burned.",
    "White Smoke": "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.",
    "Wonder Guard": "The Pokémon is immune to damaging moves that are not super effective.",
    "Adaptability": "Powers up moves of the same type as the Pokémon.",
    "Aftermath": "Damages the attacker if it contacts the Pokémon with a finishing hit.",
    "Anger Point": "A critical hit maxes the Pokémon's Attack stat.",
    "Anticipation": "The Pokémon can sense an opposing Pokémon's super effective moves.",
    "Bad Dreams": "Damages sleeping opposing Pokémon.",
    "Download": "Boosts the Pokémon's Attack or Sp. Atk stat based on the opposing Pokémon's Defense and Sp. Def stats.",
    "Dry Skin": "Restores the Pokémon's HP in rain, or when hit by a Water-type move. Damages the Pokémon in harsh sunlight, and increases the damage received from Fire-type moves.",
    "Filter": "Reduces the damage taken from super effective moves.",
    "Flower Gift": "Boosts the Attack and Sp. Def stats of the Pokémon and its allies in harsh sunlight.",
    "Forewarn": "The Pokémon can tell one of the moves an opposing Pokémon has.",
    "Frisk": "The Pokémon knows opposing Pokémon's held items.",
    "Gluttony": "The Pokémon eats its held Berry at half HP or less.",
    "Heatproof": "The Pokémon receives half damage from Fire-type moves.",
    "Honey Gather": "The Pokémon may gather Honey after a battle.",
    "Hydration": "Heals the Pokémon's status condition in the rain.",
    "Ice Body": "Restores the Pokémon's HP in a hailstorm.",
    "Iron Fist": "Powers up the Pokémon's punching moves.",
    "Klutz": "The Pokémon cannot use any held items.",
    "Leaf Guard": "Prevents status conditions in sunny weather.",
    "Magic Guard": "The Pokémon only takes damage from attacks.",
    "Mold Breaker": "Moves can be used on the target regardless of its Abilities.",
    "Motor Drive": "Boosts its Speed stat if hit by an Electric-type, instead of taking damage.",
    "Multitype": "Changes the Pokémon's type to match the Plate or Z-Crystal it holds.",
    "No Guard": "The Pokémon employs no-guard tactics to ensure incoming and outgoing attacks always land.",
    "Normalize": "All the Pokémon's moves become Normal-type. The power of those moves is boosted a little.",
    "Poison Heal": "Restores HP if the Pokémon is poisoned, instead of losing HP.",
    "Quick Feet": "Boosts the Speed stat if the Pokémon has a status condition.",
    "Reckless": "Powers up moves that have recoil damage.",
    "Rivalry": "Becomes competitive and deals more damage to Pokémon of the same gender, but deals less to Pokémon of the opposite gender.",
    "Scrappy": "The Pokémon can hit Ghost-type Pokémon with Normal and Fighting-type moves.",
    "Simple": "The stat changes the Pokémon receives are doubled.",
    "Skill Link": "Increases the number of times multi-stike moves hit.",
    "Slow Start": "For five turns, the Pokémon's Attack and Speed stats are halved.",
    "Sniper": "Powers up moves if they become critical hits.",
    "Snow Cloak": "Boosts evasion in a hailstorm.",
    "Snow Warning": "The Pokémon summons a hailstorm when it enters a battle.",
    "Solar Power": "Boosts the Sp. Atk stat in sunny weather, but HP decreases every turn.",
    "Solid Rock": "Reduces the power of supereffective attacks taken.",
    "Stall": "The Pokémon moves after all other Pokémon do.",
    "Steadfast": "The Pokémon's determination boosts the Speed stat each time the Pokémon flinches.",
    "Storm Drain": "Draws in all Water-type moves. Instead of being hit by Water-type moves, it boosts its Sp. Atk.",
    "Super Luck": "The Pokémon is so lucky that the critical-hit ratios of its moves are boosted.",
    "Tangled Feet": "Raises evasion if the Pokémon is confused.",
    "Technician": "Powers up the Pokémon's weaker moves.",
    "Unaware": "When attacking, the Pokémon ignores the target Pokémon's stat changes.",
    "Unburden": "Boosts the Speed stat if the Pokémon's held item is used or lost.",
    "Analytic": "Boosts move power when the Pokémon moves last.",
    "Big Pecks": "Protects the Pokémon from Defense-lowering effects.",
    "Contrary": "Makes stat changes have an opposite effect.",
    "Cursed Body": "May disable a move used on the Pokémon.",
    "Defeatist": "Halves the Pokémon's Attack and Sp. Atk stats when its HP becomes half or less.",
    "Defiant": "Boosts the Pokémon's Attack stat sharply when its stats are lowered.",
    "Flare Boost": "Powers up special attacks when the Pokémon is burned.",
    "Friend Guard": "Reduces damage done to allies.",
    "Harvest": "May create another Berry after one is used.",
    "Healer": "Sometimes heals an ally's status condition.",
    "Heavy Metal": "Doubles the Pokémon's weight.",
    "Illusion": "Comes out disguised as the Pokémon in the party's last spot.",
    "Imposter": "The Pokémon transforms itself into the Pokémon it's facing.",
    "Infiltrator": "Passes through the opposing Pokémon's barrier, substitute, and the like and strikes.",
    "Iron Barbs": "Inflicts damage to the attacker on contact with iron barbs.",
    "Justified": "Being hit by a Dark-type move boosts the Attack stat of the Pokémon, for justice.",
    "Light Metal": "Halves the Pokémon's weight.",
    "Magic Bounce": "Reflects status moves, instead of getting hit by them.",
    "Moody": "Raises one stat sharply and lowers another every turn.",
    "Moxie": "The Pokémon shows moxie, and that boosts the Attack stat after knocking out any Pokémon.",
    "Multiscale": "Reduces the amount of damage the Pokémon takes when its HP is full.",
    "Mummy": "Contact with the Pokémon changes the attacker's Ability to Mummy.",
    "Overcoat": "Protects the Pokémon from things like sand, hail, and powder.",
    "Pickpocket": "Steals an item from an attacker that made direct contact.",
    "Poison Touch": "May poison a target when the Pokémon makes contact.",
    "Prankster": "Gives priority to a status move.",
    "Rattled": "Dark, Ghost, and Bug-type moves scare the Pokémon and boost its Speed stat.",
    "Regenerator": "Restores a little HP when withdrawn from battle.",
    "Sand Force": "Boosts the power of Rock, Ground, and Steel-type moves in a sandstorm.",
    "Sand Rush": "Boosts the Pokémon's Speed stat in a sandstorm.",
    "Sap Sipper": "Boosts the Attack stat if hit by a Grass-type move, instead of taking damage.",
    "Sheer Force": "Removes additional effects to increase the power of moves when attacking.",
    "Telepathy": "Anticipates an ally's attack and dodges it.",
    "Teravolt": "Moves can be used on the target regardless of its Abilities.",
    "Toxic Boost": "Powers up physical attacks when the Pokémon is poisoned.",
    "Turboblaze": "Moves can be used on the target regardless of its Abilities.",
    "Unnerve": "Opponents cannot eat Berries.",
    "Victory Star": "Boosts the accuracy of the Pokémon and its allies.",
    "Weak Armor": "Physical attacks lower the Pokémon's Defense stat but raises its Speed stat.",
    "Wonder Skin": "Makes status moves more likely to miss.",
    "Zen Mode": "The Pokémon changes forme when its HP is half or less.",
        }




def get_pokemon_abilities():
    return copy.deepcopy(pokemon_abilities)
